services:
  - type: web
    name: oceanheart-auth
    env: ruby
    buildCommand: bundle install && rails db:migrate
    startCommand: rails server -h 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oceanheart-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: oceanheart-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: COOKIE_DOMAIN
        value: .oceanheart.ai
      - key: AUTH_URL
        value: https://oceanheart-auth.onrender.com
    healthCheckPath: /up

databases:
  - name: oceanheart-db
    databaseName: oceanheart_auth_production
    plan: free

services:
  - type: redis
    name: oceanheart-redis
    plan: free