services:
  - type: web
    name: passport-hono
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 3000
      - key: COOKIE_DOMAIN
        value: .oceanheart.ai
      - key: JWT_ISSUER
        value: passport.oceanheart.ai
      - key: RATE_LIMIT_SIGNIN_ATTEMPTS
        value: 10
      - key: RATE_LIMIT_SIGNIN_WINDOW_MS
        value: 180000
      - key: DATABASE_URL
        fromDatabase:
          name: passport-postgres
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: passport-postgres
    databaseName: passport_hono
    user: passport_user
    region: oregon
    plan: starter