version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://passport:passport@postgres:5432/passport_buffalo?sslmode=disable
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SESSION_SECRET: ${SESSION_SECRET}
      GO_ENV: ${GO_ENV:-development}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./templates:/root/templates:ro
      - ./public:/root/public:ro

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: passport_buffalo
      POSTGRES_USER: passport
      POSTGRES_PASSWORD: passport
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: